#set the date variables
RTC_SECONDS := $(shell date -u +%-S)
RTC_MINUTES := $(shell date -u +%-M)
RTC_HOURS := $(shell date -u +%-H)
RTC_DAYS := $(shell date -u +%-d)
RTC_WEEKDAY := $(shell date -u +%A | tr a-z A-Z)
RTC_MONTH := $(shell date -u +%B | tr a-z A-Z)
RTC_YEAR := $(shell date -u +%Y)


CFLAGS = -DRTC_SECONDS=$(RTC_SECONDS) -DRTC_MINUTES=$(RTC_MINUTES) -DRTC_HOURS=$(RTC_HOURS) -DRTC_DAYS=$(RTC_DAYS) -DRTC_WEEKDAY=$(RTC_WEEKDAY) -DRTC_MONTH=$(RTC_MONTH) -DRTC_YEAR=$(RTC_YEAR)

